services:
  discord-bot:
    container_name: Bot
    image: bot
    build:
      context: .
      dockerfile: Dockerfile_bot
    restart: always
    env_file:
      - .env
    networks:
      - Starguard

  server:
    container_name: Server
    image: server
    ports:
      - ${SERVER_PORT}:5000
    build:
      context: .
      dockerfile: Dockerfile_server
    restart: always
    env_file:
      - .env
    networks:
      - Starguard

  mongodb:
    container_name: mongodb
    image: mongo
    # uncomment the 2 following lines to make accessible from outside docker
    # ports:
    #   - ${MONGO_PORT}:27017
    volumes:
      - ./server/mongo-data:/data/db
    command: mongod --noauth
    restart: always
    networks:
      - Starguard

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    restart: always
    networks:
      - Starguard

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - Starguard

networks:
  Starguard:
