services:
  discord-bot:
    container_name: Starguard-Bot
    image: starguard-bot
    build:
      context: .
      dockerfile: Dockerfile_bot
    restart: always
    env_file:
      - .env
    networks:
      - Starguard

  server:
    container_name: Starguard-Server
    image: starguard-server
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile_server
    restart: always
    env_file:
      - .env
    networks:
      - Starguard

  mongodb:
    container_name: mongodb
    image: mongo
    #uncomment the 2 following lines to make accessible from outside docker
    #ports:
    #  - 27017:27017
    volumes:
      - ./server/mongo-data:/data/db
    command: mongod --noauth
    restart: always
    networks:
      - Starguard

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    restart: always
    networks:
      - Starguard

networks:
  Starguard:
