FROM python:3.10

WORKDIR /app

COPY bot/bot.py /app/
COPY .env /app/

RUN python -m pip install --upgrade pip

RUN pip install discord-py-interactions python-dotenv interactions.py requests

CMD ["python", "bot.py"]
