FROM python:3.10

WORKDIR /app

COPY bot/bot.py /app/
COPY bot/messages.py /app/
COPY .env.example /app/.env

RUN python -m pip install --upgrade pip

RUN pip install discord-py-interactions python-dotenv interactions.py requests pymongo

CMD ["python", "bot.py"]
