FROM python:3.12-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

COPY requirements.txt ./
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY common/ ./common/
COPY server/ ./server/

RUN useradd --create-home --uid 10001 starguard
USER starguard

EXPOSE 5000

CMD ["python", "-m", "server.server"]
