version: "3.9"
services:
  discord-bot:
    container_name: StarGuardBot
    image: bot
    build:
      context: .
      dockerfile: Dockerfile_bot
    restart: always
    env_file:
      - .env
    networks:
      - Starguard

  server:
    container_name: StarGuardServer
    image: server
    ports:
      - ${SERVER_PORT}:5000
    build:
      context: .
      dockerfile: Dockerfile_server
    restart: always
    env_file:
      - .env
    networks:
      - Starguard

networks:
  Starguard:
