name: Publish Docker images to ghcr.io

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for bot
        run: |
          docker build -f Dockerfile_bot -t starguard-bot .

      - name: Tag and push bot image
        run: |
          docker tag starguard-bot:latest ghcr.io/${{ github.repository_owner }}/starguard-bot:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/starguard-bot:${{ github.sha }}
          docker tag starguard-bot:latest ghcr.io/${{ github.repository_owner }}/starguard-bot:latest
          docker push ghcr.io/${{ github.repository_owner }}/starguard-bot:latest

  build-and-push-image-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for server
        run: |
          docker build -f Dockerfile_server -t starguard-server .

      - name: Tag and push server image
        run: |
          docker tag starguard-server:latest ghcr.io/${{ github.repository_owner }}/starguard-server:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/starguard-server:${{ github.sha }}
          docker tag starguard-server:latest ghcr.io/${{ github.repository_owner }}/starguard-server:latest
          docker push ghcr.io/${{ github.repository_owner }}/starguard-server:latest
